name: counter_app
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.4.0
  json_annotation: ^4.8.0
  riverpod: ^2.4.0

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.0.0
  custom_lint: ^0.5.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.3.2

flutter:
  uses-material-design: true